import type {
  Auction,
  BookingReference,
  Contract,
  DashboardData,
  RfiType,
  RfqType,
  RfqResponse,
  UserProfile,
  VendorOption,
} from '@auction/types'

const now = Date.now()
const iso = (offsetMs: number) => new Date(now + offsetMs).toISOString()
const dateOnly = (offsetMs: number) => new Date(now + offsetMs).toISOString().slice(0, 10)

export const MOCK_USERS: UserProfile[] = [
  {
    id: 'u-ops-1',
    name: 'Arjun Mehta',
    email: 'ops@optimile-demo.com',
    mobile: '9876501001',
    tenantName: 'Hindustan FMCG Ltd',
    role: 'OPS',
    status: 'ACTIVE',
  },
  {
    id: 'u-proc-1',
    name: 'Naina Kapoor',
    email: 'procurement@optimile-demo.com',
    mobile: '9876501002',
    tenantName: 'Hindustan FMCG Ltd',
    role: 'PROCUREMENT',
    status: 'ACTIVE',
  },
  {
    id: 'u-admin-1',
    name: 'Samar Verma',
    email: 'admin@optimile-demo.com',
    mobile: '9876501003',
    tenantName: 'Hindustan FMCG Ltd',
    role: 'ADMIN',
    status: 'ACTIVE',
  },
]

export const MOCK_VENDORS: VendorOption[] = [
  { id: 'ven-1', name: 'SwiftHaul Logistics', score: 92 },
  { id: 'ven-2', name: 'BlueAxle Freight', score: 88 },
  { id: 'ven-3', name: 'RoadBridge Carriers', score: 84 },
  { id: 'ven-4', name: 'MetroFleet Movers', score: 79 },
]

export const MOCK_BOOKINGS: BookingReference[] = [
  {
    id: 'BK-2026-11203',
    lane: 'Mumbai → Delhi',
    vehicleType: '20 MT Open Body',
    commodity: 'FMCG - packaged snacks',
    quantity: 18,
    uom: 'Metric Tonnes',
    loadingDate: dateOnly(2 * 24 * 60 * 60 * 1000),
    status: 'PENDING_AUCTION',
  },
  {
    id: 'BK-2026-11261',
    lane: 'Pune → Jaipur',
    vehicleType: '32 FT Closed Body',
    commodity: 'Consumer durables',
    quantity: 22,
    uom: 'Metric Tonnes',
    loadingDate: dateOnly(3 * 24 * 60 * 60 * 1000),
    status: 'PENDING_AUCTION',
  },
]

export const MOCK_DASHBOARD: DashboardData = {
  liveAuctions: {
    label: 'Live Auctions',
    value: 0,
    insight: 'No auctions are live in the seed data right now.',
  },
  pendingAwards: {
    label: 'Pending Awards',
    value: 3,
    insight: '1 Spot, 1 Bulk, and 1 Lot auction are pending award.',
  },
  expiringContracts: {
    label: 'Expiring Contracts',
    value: 4,
    insight: '4 contracts enter the 30-day warning window this month.',
  },
}

export const MOCK_AUCTIONS: Auction[] = [
  {
    id: 'AUC-SPOT-042',
    title: 'Spot | BK-2026-11203 | Mumbai → Delhi',
    type: 'SPOT',
    status: 'COMPLETED',
    createdBy: 'Arjun Mehta',
    createdByRole: 'OPS',
    createdAt: iso(-2 * 60 * 60 * 1000),
    startAt: iso(-15 * 60 * 1000),
    minBidDecrement: 200,
    extensionTriggerMinutes: 5,
    extensionDurationMinutes: 5,
    maxExtensions: 3,
    biddingWindowMinutes: 20,
    bookingId: 'BK-2026-11203',
    completedAt: iso(-5 * 60 * 1000),
    awardDeadline: iso(2 * 60 * 60 * 1000),
    invitedVendorIds: ['ven-1', 'ven-2', 'ven-3'],
    lanes: [
      {
        id: 'lane-spot-1',
        lane: 'Mumbai → Delhi',
        region: 'North India',
        vehicleType: '20 MT Open Body',
        capacityMt: 20,
        rateUnit: 'PER_TRIP',
        ceilingRate: 52000,
        estimatedTrips: 1,
        basePriceSource: 'MANUAL',
        allocationMode: 'SINGLE',
        allocation: { l1: 100, l2: 0, l3: 0 },
        eligibleVendorIds: ['ven-1', 'ven-2', 'ven-3'],
        timerEndsAt: iso(12 * 60 * 1000),
        extensionCount: 1,
        bidCount: 9,
        ranking: [
          { rank: 1, vendorId: 'ven-2', vendorName: 'BlueAxle Freight', amount: 48600, timestamp: iso(-2 * 60 * 1000) },
          { rank: 2, vendorId: 'ven-1', vendorName: 'SwiftHaul Logistics', amount: 48900, timestamp: iso(-4 * 60 * 1000) },
          { rank: 3, vendorId: 'ven-3', vendorName: 'RoadBridge Carriers', amount: 49300, timestamp: iso(-8 * 60 * 1000) },
        ],
      },
    ],
    auditTrail: [
      { id: 'e1', type: 'CREATED', message: 'Spot auction draft created from booking BK-2026-11203.', actor: 'Arjun Mehta', timestamp: iso(-2 * 60 * 60 * 1000) },
      { id: 'e2', type: 'LAUNCHED', message: 'Auction launched with 3 invited vendors.', actor: 'Arjun Mehta', timestamp: iso(-15 * 60 * 1000) },
      { id: 'e3', type: 'EXTENDED', message: 'Timer extended by 5 minutes after a valid bid in the final window.', actor: 'System', timestamp: iso(-2 * 60 * 1000) },
      { id: 'e4', type: 'COMPLETED', message: 'Auction completed and is pending award.', actor: 'System', timestamp: iso(-5 * 60 * 1000) },
    ],
  },
  {
    id: 'AUC-BULK-018',
    title: 'Bulk | South Corridor Contract Rates',
    type: 'BULK',
    status: 'COMPLETED',
    createdBy: 'Naina Kapoor',
    createdByRole: 'PROCUREMENT',
    createdAt: iso(-5 * 24 * 60 * 60 * 1000),
    startAt: iso(-3 * 24 * 60 * 60 * 1000),
    completedAt: iso(-8 * 60 * 60 * 1000),
    contractStartDate: dateOnly(35 * 24 * 60 * 60 * 1000),
    contractEndDate: dateOnly(215 * 24 * 60 * 60 * 1000),
    minBidDecrement: 200,
    extensionTriggerMinutes: 5,
    extensionDurationMinutes: 5,
    maxExtensions: 3,
    biddingWindowMinutes: 2880,
    awardDeadline: iso(3 * 24 * 60 * 60 * 1000),
    invitedVendorIds: ['ven-1', 'ven-2', 'ven-3', 'ven-4'],
    lanes: [
      {
        id: 'lane-bulk-1',
        lane: 'Mumbai → Bangalore',
        region: 'South India',
        vehicleType: '20 MT Open Body',
        capacityMt: 20,
        rateUnit: 'PER_TRIP',
        ceilingRate: 10000,
        estimatedTrips: 400,
        basePriceSource: 'MANUAL',
        allocationMode: 'SINGLE',
        allocation: { l1: 100, l2: 0, l3: 0 },
        eligibleVendorIds: ['ven-1', 'ven-2', 'ven-3'],
        timerEndsAt: iso(-8 * 60 * 60 * 1000),
        extensionCount: 2,
        bidCount: 11,
        ranking: [
          { rank: 1, vendorId: 'ven-2', vendorName: 'BlueAxle Freight', amount: 9100, timestamp: iso(-10 * 60 * 60 * 1000) },
          { rank: 2, vendorId: 'ven-1', vendorName: 'SwiftHaul Logistics', amount: 9300, timestamp: iso(-11 * 60 * 60 * 1000) },
          { rank: 3, vendorId: 'ven-3', vendorName: 'RoadBridge Carriers', amount: 9500, timestamp: iso(-12 * 60 * 60 * 1000) },
        ],
      },
    ],
    auditTrail: [
      { id: 'e4', type: 'CREATED', message: 'Bulk auction draft created for 1 lane.', actor: 'Naina Kapoor', timestamp: iso(-5 * 24 * 60 * 60 * 1000) },
      { id: 'e5', type: 'LAUNCHED', message: 'Auction launched in sealed mode.', actor: 'Naina Kapoor', timestamp: iso(-3 * 24 * 60 * 60 * 1000) },
      { id: 'e6', type: 'COMPLETED', message: 'Auction completed and ranking frozen for award.', actor: 'System', timestamp: iso(-8 * 60 * 60 * 1000) },
    ],
  },
  {
    id: 'AUC-LOT-011',
    title: 'Lot | North India Regional Procurement',
    type: 'LOT',
    status: 'COMPLETED',
    createdBy: 'Naina Kapoor',
    createdByRole: 'PROCUREMENT',
    createdAt: iso(-15 * 24 * 60 * 60 * 1000),
    startAt: iso(-13 * 24 * 60 * 60 * 1000),
    completedAt: iso(-10 * 24 * 60 * 60 * 1000),
    contractStartDate: dateOnly(-4 * 24 * 60 * 60 * 1000),
    contractEndDate: dateOnly(175 * 24 * 60 * 60 * 1000),
    minBidDecrement: 250,
    extensionTriggerMinutes: 5,
    extensionDurationMinutes: 5,
    maxExtensions: 3,
    biddingWindowMinutes: 2880,
    region: 'North India',
    awardDeadline: iso(-8 * 24 * 60 * 60 * 1000),
    invitedVendorIds: ['ven-1', 'ven-2', 'ven-3', 'ven-4'],
    lanes: [
      {
        id: 'lane-lot-1',
        lane: 'Delhi → Lucknow',
        region: 'North India',
        vehicleType: '32 FT Closed Body',
        capacityMt: 32,
        rateUnit: 'PER_MT',
        ceilingRate: 14500,
        estimatedTrips: 220,
        basePriceSource: 'MANUAL',
        allocationMode: 'SPLIT',
        allocation: { l1: 70, l2: 20, l3: 10 },
        eligibleVendorIds: ['ven-1', 'ven-2', 'ven-4'],
        timerEndsAt: iso(-10 * 24 * 60 * 60 * 1000),
        extensionCount: 1,
        bidCount: 8,
        ranking: [
          { rank: 1, vendorId: 'ven-4', vendorName: 'MetroFleet Movers', amount: 12900, timestamp: iso(-10 * 24 * 60 * 60 * 1000) },
          { rank: 2, vendorId: 'ven-2', vendorName: 'BlueAxle Freight', amount: 13100, timestamp: iso(-10.1 * 24 * 60 * 60 * 1000) },
          { rank: 3, vendorId: 'ven-1', vendorName: 'SwiftHaul Logistics', amount: 13250, timestamp: iso(-10.2 * 24 * 60 * 60 * 1000) },
        ],
      },
    ],
    auditTrail: [
      { id: 'e7', type: 'CREATED', message: 'Lot auction created for North India lanes.', actor: 'Naina Kapoor', timestamp: iso(-15 * 24 * 60 * 60 * 1000) },
      { id: 'e8', type: 'LAUNCHED', message: 'Auction launched and vendors notified.', actor: 'Naina Kapoor', timestamp: iso(-13 * 24 * 60 * 60 * 1000) },
      { id: 'e9', type: 'COMPLETED', message: 'Auction completed.', actor: 'System', timestamp: iso(-10 * 24 * 60 * 60 * 1000) },
      { id: 'e10', type: 'OVERRIDE', message: 'Award pending for Delhi → Lucknow with selected mappings frozen.', actor: 'Naina Kapoor', timestamp: iso(-9 * 24 * 60 * 60 * 1000) },
    ],
  },
  {
    id: 'AUC-BULK-019',
    title: 'Bulk | West Zone Replenishment',
    type: 'BULK',
    status: 'NO_BIDS',
    createdBy: 'Naina Kapoor',
    createdByRole: 'PROCUREMENT',
    createdAt: iso(-4 * 24 * 60 * 60 * 1000),
    startAt: iso(-2 * 24 * 60 * 60 * 1000),
    completedAt: iso(-12 * 60 * 60 * 1000),
    contractStartDate: dateOnly(30 * 24 * 60 * 60 * 1000),
    contractEndDate: dateOnly(210 * 24 * 60 * 60 * 1000),
    minBidDecrement: 200,
    extensionTriggerMinutes: 5,
    extensionDurationMinutes: 5,
    maxExtensions: 3,
    biddingWindowMinutes: 1440,
    awardDeadline: iso(2 * 24 * 60 * 60 * 1000),
    invitedVendorIds: ['ven-3', 'ven-4'],
    lanes: [
      {
        id: 'lane-bulk-3',
        lane: 'Ahmedabad → Surat',
        region: 'West India',
        vehicleType: 'LCV',
        capacityMt: 8,
        rateUnit: 'PER_TRIP',
        ceilingRate: 6200,
        estimatedTrips: 180,
        basePriceSource: 'MANUAL',
        allocationMode: 'SINGLE',
        allocation: { l1: 100, l2: 0, l3: 0 },
        eligibleVendorIds: ['ven-3', 'ven-4'],
        timerEndsAt: iso(-12 * 60 * 60 * 1000),
        extensionCount: 0,
        bidCount: 0,
        ranking: [],
      },
    ],
    auditTrail: [
      { id: 'e12', type: 'CREATED', message: 'Bulk auction draft created.', actor: 'Naina Kapoor', timestamp: iso(-4 * 24 * 60 * 60 * 1000) },
      { id: 'e13', type: 'LAUNCHED', message: 'Auction launched.', actor: 'Naina Kapoor', timestamp: iso(-2 * 24 * 60 * 60 * 1000) },
      { id: 'e14', type: 'COMPLETED', message: 'Auction ended with zero valid bids.', actor: 'System', timestamp: iso(-12 * 60 * 60 * 1000) },
    ],
  },
  {
    id: 'AUC-SPOT-055',
    title: 'Spot | Ahmedabad → Vadodara',
    type: 'SPOT',
    status: 'LIVE',
    createdBy: 'Arjun Mehta',
    createdByRole: 'OPS',
    createdAt: iso(-90 * 60 * 1000),
    startAt: iso(-20 * 60 * 1000),
    minBidDecrement: 200,
    extensionTriggerMinutes: 5,
    extensionDurationMinutes: 5,
    maxExtensions: 3,
    biddingWindowMinutes: 45,
    bookingId: 'BK-2026-11261',
    awardDeadline: iso(5 * 60 * 60 * 1000),
    invitedVendorIds: ['ven-1', 'ven-2'],
    lanes: [
      {
        id: 'lane-spot-55',
        lane: 'Ahmedabad → Vadodara',
        region: 'West India',
        vehicleType: 'LCV',
        capacityMt: 8,
        rateUnit: 'PER_TRIP',
        ceilingRate: 9800,
        estimatedTrips: 1,
        basePriceSource: 'MANUAL',
        allocationMode: 'SINGLE',
        allocation: { l1: 100, l2: 0, l3: 0 },
        eligibleVendorIds: ['ven-1', 'ven-2'],
        timerEndsAt: iso(25 * 60 * 1000),
        extensionCount: 0,
        bidCount: 4,
        ranking: [{ rank: 1, vendorId: 'ven-2', vendorName: 'BlueAxle Freight', amount: 9200, timestamp: iso(-3 * 60 * 1000) }],
      },
    ],
    auditTrail: [
      { id: 'e55-1', type: 'CREATED', message: 'Spot auction created.', actor: 'Arjun Mehta', timestamp: iso(-90 * 60 * 1000) },
      { id: 'e55-2', type: 'LAUNCHED', message: 'Auction launched.', actor: 'Arjun Mehta', timestamp: iso(-20 * 60 * 1000) },
    ],
  },
  {
    id: 'AUC-BULK-031',
    title: 'Bulk | Chennai → Coimbatore',
    type: 'BULK',
    status: 'DRAFT',
    createdBy: 'Naina Kapoor',
    createdByRole: 'PROCUREMENT',
    createdAt: iso(-6 * 60 * 60 * 1000),
    startAt: iso(10 * 60 * 60 * 1000),
    minBidDecrement: 200,
    extensionTriggerMinutes: 5,
    extensionDurationMinutes: 5,
    maxExtensions: 3,
    biddingWindowMinutes: 1440,
    awardDeadline: iso(3 * 24 * 60 * 60 * 1000),
    invitedVendorIds: ['ven-2', 'ven-3', 'ven-4'],
    lanes: [],
    auditTrail: [
      { id: 'e31-1', type: 'CREATED', message: 'Bulk auction saved as draft.', actor: 'Naina Kapoor', timestamp: iso(-6 * 60 * 60 * 1000) },
    ],
  },
  {
    id: 'AUC-LOT-025',
    title: 'Lot | Jaipur Regional Procurement',
    type: 'LOT',
    status: 'AWARDED',
    createdBy: 'Naina Kapoor',
    createdByRole: 'PROCUREMENT',
    createdAt: iso(-12 * 24 * 60 * 60 * 1000),
    startAt: iso(-11 * 24 * 60 * 60 * 1000),
    completedAt: iso(-9 * 24 * 60 * 60 * 1000),
    minBidDecrement: 250,
    extensionTriggerMinutes: 5,
    extensionDurationMinutes: 5,
    maxExtensions: 3,
    biddingWindowMinutes: 2880,
    awardDeadline: iso(-7 * 24 * 60 * 60 * 1000),
    invitedVendorIds: ['ven-1', 'ven-3'],
    lanes: [
      {
        id: 'lane-lot-25',
        lane: 'Jaipur → Udaipur',
        region: 'North India',
        vehicleType: '20 MT Open Body',
        capacityMt: 20,
        rateUnit: 'PER_TRIP',
        ceilingRate: 28000,
        estimatedTrips: 60,
        basePriceSource: 'MANUAL',
        allocationMode: 'SINGLE',
        allocation: { l1: 100, l2: 0, l3: 0 },
        eligibleVendorIds: ['ven-1', 'ven-3'],
        timerEndsAt: iso(-9 * 24 * 60 * 60 * 1000),
        extensionCount: 0,
        bidCount: 5,
        ranking: [{ rank: 1, vendorId: 'ven-1', vendorName: 'SwiftHaul Logistics', amount: 26400, timestamp: iso(-9 * 24 * 60 * 60 * 1000) }],
      },
    ],
    auditTrail: [
      { id: 'e25-1', type: 'CREATED', message: 'Lot auction created.', actor: 'Naina Kapoor', timestamp: iso(-12 * 24 * 60 * 60 * 1000) },
      { id: 'e25-2', type: 'COMPLETED', message: 'Auction completed.', actor: 'System', timestamp: iso(-9 * 24 * 60 * 60 * 1000) },
      { id: 'e25-3', type: 'AWARDED', message: 'Auction awarded.', actor: 'Naina Kapoor', timestamp: iso(-8 * 24 * 60 * 60 * 1000) },
    ],
  },
  {
    id: 'AUC-SPOT-061',
    title: 'Spot | Nashik → Surat',
    type: 'SPOT',
    status: 'CANCELLED',
    createdBy: 'Arjun Mehta',
    createdByRole: 'OPS',
    createdAt: iso(-30 * 60 * 60 * 1000),
    startAt: iso(-28 * 60 * 60 * 1000),
    minBidDecrement: 200,
    extensionTriggerMinutes: 5,
    extensionDurationMinutes: 5,
    maxExtensions: 3,
    biddingWindowMinutes: 30,
    bookingId: 'BK-2026-11203',
    awardDeadline: iso(-24 * 60 * 60 * 1000),
    invitedVendorIds: ['ven-2', 'ven-4'],
    lanes: [],
    auditTrail: [
      { id: 'e61-1', type: 'CREATED', message: 'Spot auction created.', actor: 'Arjun Mehta', timestamp: iso(-30 * 60 * 60 * 1000) },
      { id: 'e61-2', type: 'CANCELLED', message: 'Auction cancelled by procurement.', actor: 'Arjun Mehta', timestamp: iso(-27 * 60 * 60 * 1000) },
    ],
  },
]

export const MOCK_CONTRACTS: Contract[] = [
  {
    id: 'CNT-2026-0101',
    sourceAuctionId: 'AUC-LEGACY-LOT-001',
    contractType: 'LOT',
    vendorId: 'ven-2',
    vendorName: 'BlueAxle Freight',
    lane: 'Delhi → Lucknow',
    region: 'North India',
    vehicleType: '32 FT Closed Body',
    contractedRate: 13100,
    rateUnit: 'PER_MT',
    volumeAllocationPercent: 70,
    allocationRank: 'L1',
    startDate: dateOnly(-4 * 24 * 60 * 60 * 1000),
    endDate: dateOnly(175 * 24 * 60 * 60 * 1000),
    estimatedTrips: 220,
    status: 'ACTIVE',
    l1OverrideReason: 'R1 assigned to the R2 bidder due to recent placement failure scorecard for MetroFleet Movers.',
    rateSyncedToTms: true,
    placementFailures: [],
    rateDeviationOpen: false,
  },
  {
    id: 'CNT-2026-0102',
    sourceAuctionId: 'AUC-LEGACY-LOT-001',
    contractType: 'LOT',
    vendorId: 'ven-4',
    vendorName: 'MetroFleet Movers',
    lane: 'Delhi → Lucknow',
    region: 'North India',
    vehicleType: '32 FT Closed Body',
    contractedRate: 12900,
    rateUnit: 'PER_MT',
    volumeAllocationPercent: 20,
    allocationRank: 'L2',
    startDate: dateOnly(-4 * 24 * 60 * 60 * 1000),
    endDate: dateOnly(175 * 24 * 60 * 60 * 1000),
    estimatedTrips: 220,
    status: 'ACTIVE',
    rateSyncedToTms: true,
    placementFailures: [],
    rateDeviationOpen: false,
  },
  {
    id: 'CNT-2026-0103',
    sourceAuctionId: 'AUC-LEGACY-LOT-001',
    contractType: 'LOT',
    vendorId: 'ven-1',
    vendorName: 'SwiftHaul Logistics',
    lane: 'Delhi → Lucknow',
    region: 'North India',
    vehicleType: '32 FT Closed Body',
    contractedRate: 13250,
    rateUnit: 'PER_MT',
    volumeAllocationPercent: 10,
    allocationRank: 'L3',
    startDate: dateOnly(-4 * 24 * 60 * 60 * 1000),
    endDate: dateOnly(175 * 24 * 60 * 60 * 1000),
    estimatedTrips: 220,
    status: 'ACTIVE',
    rateSyncedToTms: true,
    placementFailures: [],
    rateDeviationOpen: false,
  },
  {
    id: 'CNT-2026-0117',
    sourceAuctionId: 'AUC-LEGACY-BULK-001',
    contractType: 'BULK',
    vendorId: 'ven-3',
    vendorName: 'RoadBridge Carriers',
    lane: 'Pune → Jaipur',
    region: 'West India',
    vehicleType: '32 FT Closed Body',
    contractedRate: 48800,
    rateUnit: 'PER_TRIP',
    volumeAllocationPercent: 100,
    allocationRank: 'L1',
    startDate: dateOnly(-40 * 24 * 60 * 60 * 1000),
    endDate: dateOnly(10 * 24 * 60 * 60 * 1000),
    estimatedTrips: 75,
    status: 'EXPIRING_SOON',
    rateSyncedToTms: true,
    placementFailures: [
      {
        failedVendor: 'RoadBridge Carriers',
        replacementVendor: 'BlueAxle Freight',
        originalRate: 48800,
        replacementRate: 51200,
        differential: 2400,
        debitNoteTriggered: true,
      },
    ],
    rateDeviationOpen: true,
  },
]

export const MOCK_RFIS: RfiType[] = [
  {
    id: 'RFI-2026-014',
    title: 'Q2 Bulk lanes — capacity discovery',
    description: 'Discovering vendor capacity and equipment readiness for Pune → Jaipur and Mumbai → Delhi BULK lanes for the upcoming quarter.',
    deadline: iso(7 * 24 * 60 * 60 * 1000),
    status: 'PUBLISHED',
    targetEmails: ['ops@swifthaul.com', 'sales@blueaxle.com', 'bd@roadbridge.com'],
    messageToVendor: 'Share your fleet availability and indicative rates for the listed lanes.',
    templateFileName: 'q2-bulk-rfi-template.xlsx',
    vendorTracking: [
      { vendorIdOrEmail: 'ven-1', name: 'SwiftHaul Logistics', status: 'RESPONDED' },
      { vendorIdOrEmail: 'ven-2', name: 'BlueAxle Freight', status: 'PENDING' },
      { vendorIdOrEmail: 'ven-3', name: 'RoadBridge Carriers', status: 'RESPONDED' },
    ],
    createdAt: iso(-3 * 24 * 60 * 60 * 1000),
    createdBy: 'u-proc-1',
  },
  {
    id: 'RFI-2026-013',
    title: 'New origin Hyderabad — vendor onboarding',
    description: 'Capacity sourcing for new Hyderabad cluster.',
    deadline: iso(14 * 24 * 60 * 60 * 1000),
    status: 'DRAFT',
    targetEmails: [],
    vendorTracking: [],
    createdAt: iso(-1 * 24 * 60 * 60 * 1000),
    createdBy: 'u-proc-1',
  },
  {
    id: 'RFI-2026-011',
    title: 'Cold-chain capability survey',
    description: 'Closed RFI for reefer-equipped fleets in West India.',
    deadline: iso(-2 * 24 * 60 * 60 * 1000),
    status: 'CLOSED',
    targetEmails: ['ops@swifthaul.com', 'bd@roadbridge.com'],
    vendorTracking: [
      { vendorIdOrEmail: 'ven-1', name: 'SwiftHaul Logistics', status: 'RESPONDED' },
      { vendorIdOrEmail: 'ven-3', name: 'RoadBridge Carriers', status: 'DECLINED' },
    ],
    createdAt: iso(-21 * 24 * 60 * 60 * 1000),
    createdBy: 'u-proc-1',
  },
]

export const MOCK_RFQS: RfqType[] = [
  {
    id: 'RFQ-2026-022',
    title: 'Q2 Bulk freight rates — Pune & Mumbai lanes',
    deadline: iso(5 * 24 * 60 * 60 * 1000),
    status: 'PUBLISHED',
    targetEmails: ['ops@swifthaul.com', 'sales@blueaxle.com', 'bd@roadbridge.com', 'rfq@metrofleet.com'],
    messageToVendor: 'Submit per-trip and per-MT rates for the listed lanes. GST exclusive.',
    templateFileName: 'q2-bulk-rfq-template.xlsx',
    vendorTracking: [
      { vendorIdOrEmail: 'ven-1', name: 'SwiftHaul Logistics', status: 'RESPONDED' },
      { vendorIdOrEmail: 'ven-2', name: 'BlueAxle Freight', status: 'RESPONDED' },
      { vendorIdOrEmail: 'ven-3', name: 'RoadBridge Carriers', status: 'PENDING' },
      { vendorIdOrEmail: 'ven-4', name: 'MetroFleet Movers', status: 'RESPONDED' },
    ],
    createdAt: iso(-5 * 24 * 60 * 60 * 1000),
    createdBy: 'u-proc-1',
  },
  {
    id: 'RFQ-2026-021',
    title: 'Spot — Bangalore → Chennai express',
    deadline: iso(-1 * 24 * 60 * 60 * 1000),
    status: 'EVALUATING',
    targetEmails: ['ops@swifthaul.com', 'sales@blueaxle.com'],
    vendorTracking: [
      { vendorIdOrEmail: 'ven-1', name: 'SwiftHaul Logistics', status: 'RESPONDED' },
      { vendorIdOrEmail: 'ven-2', name: 'BlueAxle Freight', status: 'RESPONDED' },
    ],
    createdAt: iso(-8 * 24 * 60 * 60 * 1000),
    createdBy: 'u-ops-1',
  },
  {
    id: 'RFQ-2026-020',
    title: 'Delhi → Lucknow LOT contract',
    deadline: iso(-10 * 24 * 60 * 60 * 1000),
    status: 'AWARDED',
    targetEmails: ['ops@swifthaul.com', 'sales@blueaxle.com', 'bd@roadbridge.com'],
    vendorTracking: [
      { vendorIdOrEmail: 'ven-1', name: 'SwiftHaul Logistics', status: 'RESPONDED' },
      { vendorIdOrEmail: 'ven-2', name: 'BlueAxle Freight', status: 'RESPONDED' },
      { vendorIdOrEmail: 'ven-3', name: 'RoadBridge Carriers', status: 'DECLINED' },
    ],
    createdAt: iso(-30 * 24 * 60 * 60 * 1000),
    createdBy: 'u-proc-1',
  },
]

export const MOCK_RFQ_RESPONSES: RfqResponse[] = [
  {
    id: 'RFQR-1001',
    fileName: 'swifthaul-q2-rates.xlsx',
    vendorName: 'SwiftHaul Logistics',
    rfqId: 'RFQ-2026-022',
    uploadedAt: iso(-4 * 24 * 60 * 60 * 1000),
    uploadedBy: 'ops@swifthaul.com',
    rows: [
      { lane: 'Pune → Jaipur', vehicleType: '32 FT Closed Body', price: 48500 },
      { lane: 'Mumbai → Delhi', vehicleType: '20 MT Open Body', price: 62200 },
    ],
  },
  {
    id: 'RFQR-1002',
    fileName: 'blueaxle-q2-rates.xlsx',
    vendorName: 'BlueAxle Freight',
    rfqId: 'RFQ-2026-022',
    uploadedAt: iso(-3 * 24 * 60 * 60 * 1000),
    uploadedBy: 'sales@blueaxle.com',
    rows: [
      { lane: 'Pune → Jaipur', vehicleType: '32 FT Closed Body', price: 49100 },
      { lane: 'Mumbai → Delhi', vehicleType: '20 MT Open Body', price: 61800 },
    ],
  },
  {
    id: 'RFQR-1003',
    fileName: 'metrofleet-q2-rates.xlsx',
    vendorName: 'MetroFleet Movers',
    rfqId: 'RFQ-2026-022',
    uploadedAt: iso(-2 * 24 * 60 * 60 * 1000),
    uploadedBy: 'rfq@metrofleet.com',
    rows: [
      { lane: 'Pune → Jaipur', vehicleType: '32 FT Closed Body', price: 48900 },
      { lane: 'Mumbai → Delhi', vehicleType: '20 MT Open Body', price: 62500 },
    ],
  },
  {
    id: 'RFQR-1004',
    fileName: 'swifthaul-spot-blr-mas.xlsx',
    vendorName: 'SwiftHaul Logistics',
    rfqId: 'RFQ-2026-021',
    uploadedAt: iso(-6 * 24 * 60 * 60 * 1000),
    uploadedBy: 'ops@swifthaul.com',
    rows: [
      { lane: 'Bangalore → Chennai', vehicleType: '20 MT Open Body', price: 28500 },
    ],
  },
  {
    id: 'RFQR-1005',
    fileName: 'blueaxle-spot-blr-mas.xlsx',
    vendorName: 'BlueAxle Freight',
    rfqId: 'RFQ-2026-021',
    uploadedAt: iso(-5 * 24 * 60 * 60 * 1000),
    uploadedBy: 'sales@blueaxle.com',
    rows: [
      { lane: 'Bangalore → Chennai', vehicleType: '20 MT Open Body', price: 29200 },
    ],
  },
]

export const MOCK_DASHBOARD_RESPONSE = {
  liveAuctions: { value: 0, insight: MOCK_DASHBOARD.liveAuctions.insight },
  pendingAwards: { value: 3, insight: MOCK_DASHBOARD.pendingAwards.insight },
  expiringContracts: { value: 4, insight: MOCK_DASHBOARD.expiringContracts.insight },
  priorityAuctions: [
    { id: 'AUC-LOT-019', title: 'Bulk | LOT-Q2 | Delhi → Lucknow', type: 'LOT', status: 'AWAITING_APPROVAL', updatedAt: iso(-2 * 60 * 60 * 1000), awardDeadline: iso(2 * 24 * 60 * 60 * 1000) },
    { id: 'AUC-BULK-027', title: 'Bulk | BK-2026-11261 | Pune → Jaipur', type: 'BULK', status: 'AWAITING_APPROVAL', updatedAt: iso(-6 * 60 * 60 * 1000), awardDeadline: iso(1 * 24 * 60 * 60 * 1000) },
    { id: 'AUC-SPOT-042', title: 'Spot | BK-2026-11203 | Mumbai → Delhi', type: 'SPOT', status: 'AWAITING_APPROVAL', updatedAt: iso(-12 * 60 * 60 * 1000), awardDeadline: iso(12 * 60 * 60 * 1000) },
  ],
  expiringContractsList: [
    { id: 'CNT-2026-0117', vendorName: 'RoadBridge Carriers', lane: 'Pune → Jaipur', endDate: dateOnly(10 * 24 * 60 * 60 * 1000), status: 'EXPIRING_SOON' },
    { id: 'CNT-2026-0101', vendorName: 'BlueAxle Freight', lane: 'Delhi → Lucknow', endDate: dateOnly(28 * 24 * 60 * 60 * 1000), status: 'ACTIVE' },
    { id: 'CNT-2026-0102', vendorName: 'MetroFleet Movers', lane: 'Delhi → Lucknow', endDate: dateOnly(28 * 24 * 60 * 60 * 1000), status: 'ACTIVE' },
    { id: 'CNT-2026-0103', vendorName: 'SwiftHaul Logistics', lane: 'Delhi → Lucknow', endDate: dateOnly(28 * 24 * 60 * 60 * 1000), status: 'ACTIVE' },
  ],
}
