import type {
  Auction,
  BookingReference,
  Contract,
  DashboardData,
  UserProfile,
  VendorOption,
} from '@auction/types'

const now = Date.now()
const iso = (offsetMs: number) => new Date(now + offsetMs).toISOString()
const dateOnly = (offsetMs: number) => new Date(now + offsetMs).toISOString().slice(0, 10)

export const MOCK_USERS: UserProfile[] = [
  {
    id: 'u-ops-1',
    name: 'Arjun Mehta',
    email: 'ops@optimile-demo.com',
    mobile: '9876501001',
    tenantName: 'Hindustan FMCG Ltd',
    role: 'OPS',
    status: 'ACTIVE',
  },
  {
    id: 'u-proc-1',
    name: 'Naina Kapoor',
    email: 'procurement@optimile-demo.com',
    mobile: '9876501002',
    tenantName: 'Hindustan FMCG Ltd',
    role: 'PROCUREMENT',
    status: 'ACTIVE',
  },
  {
    id: 'u-admin-1',
    name: 'Samar Verma',
    email: 'admin@optimile-demo.com',
    mobile: '9876501003',
    tenantName: 'Hindustan FMCG Ltd',
    role: 'ADMIN',
    status: 'ACTIVE',
  },
]

export const MOCK_VENDORS: VendorOption[] = [
  { id: 'ven-1', name: 'SwiftHaul Logistics', score: 92 },
  { id: 'ven-2', name: 'BlueAxle Freight', score: 88 },
  { id: 'ven-3', name: 'RoadBridge Carriers', score: 84 },
  { id: 'ven-4', name: 'MetroFleet Movers', score: 79 },
]

export const MOCK_BOOKINGS: BookingReference[] = [
  {
    id: 'BK-2026-11203',
    lane: 'Mumbai → Delhi',
    vehicleType: '20 MT Open Body',
    commodity: 'FMCG - packaged snacks',
    quantity: 18,
    uom: 'Metric Tonnes',
    loadingDate: dateOnly(2 * 24 * 60 * 60 * 1000),
    status: 'PENDING_AUCTION',
  },
  {
    id: 'BK-2026-11261',
    lane: 'Pune → Jaipur',
    vehicleType: '32 FT Closed Body',
    commodity: 'Consumer durables',
    quantity: 22,
    uom: 'Metric Tonnes',
    loadingDate: dateOnly(3 * 24 * 60 * 60 * 1000),
    status: 'PENDING_AUCTION',
  },
]

export const MOCK_DASHBOARD: DashboardData = {
  liveAuctions: {
    label: 'Live Auctions',
    value: 0,
    insight: 'No auctions are live in the seed data right now.',
  },
  pendingAwards: {
    label: 'Pending Awards',
    value: 3,
    insight: '1 Spot, 1 Bulk, and 1 Lot auction are pending award.',
  },
  expiringContracts: {
    label: 'Expiring Contracts',
    value: 4,
    insight: '4 contracts enter the 30-day warning window this month.',
  },
}

export const MOCK_AUCTIONS: Auction[] = [
  {
    id: 'AUC-SPOT-042',
    title: 'Spot | BK-2026-11203 | Mumbai → Delhi',
    type: 'SPOT',
    status: 'COMPLETED',
    createdBy: 'Arjun Mehta',
    createdByRole: 'OPS',
    createdAt: iso(-2 * 60 * 60 * 1000),
    startAt: iso(-15 * 60 * 1000),
    minBidDecrement: 200,
    extensionTriggerMinutes: 5,
    extensionDurationMinutes: 5,
    maxExtensions: 3,
    biddingWindowMinutes: 20,
    bookingId: 'BK-2026-11203',
    completedAt: iso(-5 * 60 * 1000),
    awardDeadline: iso(2 * 60 * 60 * 1000),
    invitedVendorIds: ['ven-1', 'ven-2', 'ven-3'],
    lanes: [
      {
        id: 'lane-spot-1',
        lane: 'Mumbai → Delhi',
        region: 'North India',
        vehicleType: '20 MT Open Body',
        capacityMt: 20,
        rateUnit: 'PER_TRIP',
        ceilingRate: 52000,
        estimatedTrips: 1,
        basePriceSource: 'MANUAL',
        allocationMode: 'SINGLE',
        allocation: { r1: 100, r2: 0, r3: 0 },
        eligibleVendorIds: ['ven-1', 'ven-2', 'ven-3'],
        timerEndsAt: iso(12 * 60 * 1000),
        extensionCount: 1,
        bidCount: 9,
        ranking: [
          { rank: 1, vendorId: 'ven-2', vendorName: 'BlueAxle Freight', amount: 48600, timestamp: iso(-2 * 60 * 1000) },
          { rank: 2, vendorId: 'ven-1', vendorName: 'SwiftHaul Logistics', amount: 48900, timestamp: iso(-4 * 60 * 1000) },
          { rank: 3, vendorId: 'ven-3', vendorName: 'RoadBridge Carriers', amount: 49300, timestamp: iso(-8 * 60 * 1000) },
        ],
      },
    ],
    auditTrail: [
      { id: 'e1', type: 'CREATED', message: 'Spot auction draft created from booking BK-2026-11203.', actor: 'Arjun Mehta', timestamp: iso(-2 * 60 * 60 * 1000) },
      { id: 'e2', type: 'LAUNCHED', message: 'Auction launched with 3 invited vendors.', actor: 'Arjun Mehta', timestamp: iso(-15 * 60 * 1000) },
      { id: 'e3', type: 'EXTENDED', message: 'Timer extended by 5 minutes after a valid bid in the final window.', actor: 'System', timestamp: iso(-2 * 60 * 1000) },
      { id: 'e4', type: 'COMPLETED', message: 'Auction completed and is pending award.', actor: 'System', timestamp: iso(-5 * 60 * 1000) },
    ],
  },
  {
    id: 'AUC-BULK-018',
    title: 'Bulk | South Corridor Contract Rates',
    type: 'BULK',
    status: 'AWARDED',
    createdBy: 'Naina Kapoor',
    createdByRole: 'PROCUREMENT',
    createdAt: iso(-5 * 24 * 60 * 60 * 1000),
    startAt: iso(-3 * 24 * 60 * 60 * 1000),
    completedAt: iso(-8 * 60 * 60 * 1000),
    contractStartDate: dateOnly(35 * 24 * 60 * 60 * 1000),
    contractEndDate: dateOnly(215 * 24 * 60 * 60 * 1000),
    minBidDecrement: 200,
    extensionTriggerMinutes: 5,
    extensionDurationMinutes: 5,
    maxExtensions: 3,
    biddingWindowMinutes: 2880,
    awardDeadline: iso(3 * 24 * 60 * 60 * 1000),
    invitedVendorIds: ['ven-1', 'ven-2', 'ven-3', 'ven-4'],
    lanes: [
      {
        id: 'lane-bulk-1',
        lane: 'Mumbai → Bangalore',
        region: 'South India',
        vehicleType: '20 MT Open Body',
        capacityMt: 20,
        rateUnit: 'PER_TRIP',
        ceilingRate: 10000,
        estimatedTrips: 400,
        basePriceSource: 'MANUAL',
        allocationMode: 'SPLIT',
        allocation: { r1: 60, r2: 30, r3: 10 },
        eligibleVendorIds: ['ven-1', 'ven-2', 'ven-3'],
        timerEndsAt: iso(-8 * 60 * 60 * 1000),
        extensionCount: 2,
        bidCount: 11,
        ranking: [
          { rank: 1, vendorId: 'ven-2', vendorName: 'BlueAxle Freight', amount: 9100, timestamp: iso(-10 * 60 * 60 * 1000) },
          { rank: 2, vendorId: 'ven-1', vendorName: 'SwiftHaul Logistics', amount: 9300, timestamp: iso(-11 * 60 * 60 * 1000) },
          { rank: 3, vendorId: 'ven-3', vendorName: 'RoadBridge Carriers', amount: 9500, timestamp: iso(-12 * 60 * 60 * 1000) },
        ],
      },
      {
        id: 'lane-bulk-2',
        lane: 'Bangalore → Chennai',
        region: 'South India',
        vehicleType: '20 MT Open Body',
        capacityMt: 20,
        rateUnit: 'PER_KM',
        ceilingRate: 11000,
        estimatedTrips: 300,
        basePriceSource: 'MANUAL',
        allocationMode: 'SINGLE',
        allocation: { r1: 100, r2: 0, r3: 0 },
        eligibleVendorIds: ['ven-1', 'ven-2'],
        timerEndsAt: iso(-8 * 60 * 60 * 1000),
        extensionCount: 0,
        bidCount: 6,
        ranking: [
          { rank: 1, vendorId: 'ven-1', vendorName: 'SwiftHaul Logistics', amount: 10200, timestamp: iso(-9 * 60 * 60 * 1000) },
          { rank: 2, vendorId: 'ven-2', vendorName: 'BlueAxle Freight', amount: 10600, timestamp: iso(-9.5 * 60 * 60 * 1000) },
        ],
      },
    ],
    auditTrail: [
      { id: 'e4', type: 'CREATED', message: 'Bulk auction draft created for 2 lanes.', actor: 'Naina Kapoor', timestamp: iso(-5 * 24 * 60 * 60 * 1000) },
      { id: 'e5', type: 'LAUNCHED', message: 'Auction launched in sealed mode.', actor: 'Naina Kapoor', timestamp: iso(-3 * 24 * 60 * 60 * 1000) },
      { id: 'e6', type: 'COMPLETED', message: 'Auction completed and ranking frozen for award.', actor: 'System', timestamp: iso(-8 * 60 * 60 * 1000) },
    ],
  },
  {
    id: 'AUC-LOT-011',
    title: 'Lot | North India Regional Procurement',
    type: 'LOT',
    status: 'CANCELLED',
    createdBy: 'Naina Kapoor',
    createdByRole: 'PROCUREMENT',
    createdAt: iso(-15 * 24 * 60 * 60 * 1000),
    startAt: iso(-13 * 24 * 60 * 60 * 1000),
    completedAt: iso(-10 * 24 * 60 * 60 * 1000),
    contractStartDate: dateOnly(-4 * 24 * 60 * 60 * 1000),
    contractEndDate: dateOnly(175 * 24 * 60 * 60 * 1000),
    minBidDecrement: 250,
    extensionTriggerMinutes: 5,
    extensionDurationMinutes: 5,
    maxExtensions: 3,
    biddingWindowMinutes: 2880,
    region: 'North India',
    awardDeadline: iso(-8 * 24 * 60 * 60 * 1000),
    invitedVendorIds: ['ven-1', 'ven-2', 'ven-3', 'ven-4'],
    lanes: [
      {
        id: 'lane-lot-1',
        lane: 'Delhi → Lucknow',
        region: 'North India',
        vehicleType: '32 FT Closed Body',
        capacityMt: 32,
        rateUnit: 'PER_MT',
        ceilingRate: 14500,
        estimatedTrips: 220,
        basePriceSource: 'MANUAL',
        allocationMode: 'SPLIT',
        allocation: { r1: 70, r2: 20, r3: 10 },
        eligibleVendorIds: ['ven-1', 'ven-2', 'ven-4'],
        timerEndsAt: iso(-10 * 24 * 60 * 60 * 1000),
        extensionCount: 1,
        bidCount: 8,
        ranking: [
          { rank: 1, vendorId: 'ven-4', vendorName: 'MetroFleet Movers', amount: 12900, timestamp: iso(-10 * 24 * 60 * 60 * 1000) },
          { rank: 2, vendorId: 'ven-2', vendorName: 'BlueAxle Freight', amount: 13100, timestamp: iso(-10.1 * 24 * 60 * 60 * 1000) },
          { rank: 3, vendorId: 'ven-1', vendorName: 'SwiftHaul Logistics', amount: 13250, timestamp: iso(-10.2 * 24 * 60 * 60 * 1000) },
        ],
      },
    ],
    auditTrail: [
      { id: 'e7', type: 'CREATED', message: 'Lot auction created for North India lanes.', actor: 'Naina Kapoor', timestamp: iso(-15 * 24 * 60 * 60 * 1000) },
      { id: 'e8', type: 'LAUNCHED', message: 'Auction launched and vendors notified.', actor: 'Naina Kapoor', timestamp: iso(-13 * 24 * 60 * 60 * 1000) },
      { id: 'e9', type: 'COMPLETED', message: 'Auction completed.', actor: 'System', timestamp: iso(-10 * 24 * 60 * 60 * 1000) },
      { id: 'e10', type: 'OVERRIDE', message: 'Award pending for Delhi → Lucknow with selected mappings frozen.', actor: 'Naina Kapoor', timestamp: iso(-9 * 24 * 60 * 60 * 1000) },
    ],
  },
  {
    id: 'AUC-BULK-019',
    title: 'Bulk | West Zone Replenishment',
    type: 'BULK',
    status: 'UPCOMING',
    createdBy: 'Naina Kapoor',
    createdByRole: 'PROCUREMENT',
    createdAt: iso(-4 * 24 * 60 * 60 * 1000),
    startAt: iso(-2 * 24 * 60 * 60 * 1000),
    completedAt: iso(-12 * 60 * 60 * 1000),
    contractStartDate: dateOnly(30 * 24 * 60 * 60 * 1000),
    contractEndDate: dateOnly(210 * 24 * 60 * 60 * 1000),
    minBidDecrement: 200,
    extensionTriggerMinutes: 5,
    extensionDurationMinutes: 5,
    maxExtensions: 3,
    biddingWindowMinutes: 1440,
    awardDeadline: iso(2 * 24 * 60 * 60 * 1000),
    invitedVendorIds: ['ven-3', 'ven-4'],
    lanes: [
      {
        id: 'lane-bulk-3',
        lane: 'Ahmedabad → Surat',
        region: 'West India',
        vehicleType: 'LCV',
        capacityMt: 8,
        rateUnit: 'PER_TRIP',
        ceilingRate: 6200,
        estimatedTrips: 180,
        basePriceSource: 'MANUAL',
        allocationMode: 'SINGLE',
        allocation: { r1: 100, r2: 0, r3: 0 },
        eligibleVendorIds: ['ven-3', 'ven-4'],
        timerEndsAt: iso(-12 * 60 * 60 * 1000),
        extensionCount: 0,
        bidCount: 0,
        ranking: [],
      },
    ],
    auditTrail: [
      { id: 'e12', type: 'CREATED', message: 'Bulk auction draft created.', actor: 'Naina Kapoor', timestamp: iso(-4 * 24 * 60 * 60 * 1000) },
      { id: 'e13', type: 'LAUNCHED', message: 'Auction launched.', actor: 'Naina Kapoor', timestamp: iso(-2 * 24 * 60 * 60 * 1000) },
      { id: 'e14', type: 'COMPLETED', message: 'Auction ended with zero valid bids.', actor: 'System', timestamp: iso(-12 * 60 * 60 * 1000) },
    ],
  },
  {
    id: 'AUC-SPOT-053',
    title: 'Spot | BK-2026-11412 | Ahmedabad → Mumbai',
    type: 'SPOT',
    status: 'LIVE',
    createdBy: 'Arjun Mehta',
    createdByRole: 'OPS',
    createdAt: iso(-45 * 60 * 1000),
    startAt: iso(-15 * 60 * 1000),
    minBidDecrement: 150,
    extensionTriggerMinutes: 5,
    extensionDurationMinutes: 5,
    maxExtensions: 2,
    biddingWindowMinutes: 30,
    bookingId: 'BK-2026-11412',
    awardDeadline: iso(75 * 60 * 1000),
    invitedVendorIds: ['ven-1', 'ven-2', 'ven-4'],
    lanes: [
      {
        id: 'lane-spot-2',
        lane: 'Ahmedabad → Mumbai',
        region: 'West India',
        vehicleType: '20 MT Open Body',
        capacityMt: 20,
        rateUnit: 'PER_TRIP',
        ceilingRate: 41000,
        estimatedTrips: 1,
        basePriceSource: 'MANUAL',
        allocationMode: 'SINGLE',
        allocation: { r1: 100, r2: 0, r3: 0 },
        eligibleVendorIds: ['ven-1', 'ven-2', 'ven-4'],
        timerEndsAt: iso(15 * 60 * 1000),
        extensionCount: 0,
        bidCount: 4,
        ranking: [
          { rank: 1, vendorId: 'ven-4', vendorName: 'MetroFleet Movers', amount: 38900, timestamp: iso(-4 * 60 * 1000) },
          { rank: 2, vendorId: 'ven-1', vendorName: 'SwiftHaul Logistics', amount: 39200, timestamp: iso(-6 * 60 * 1000) },
          { rank: 3, vendorId: 'ven-2', vendorName: 'BlueAxle Freight', amount: 39500, timestamp: iso(-8 * 60 * 1000) },
        ],
      },
    ],
    auditTrail: [
      { id: 'e15', type: 'CREATED', message: 'Spot auction draft created from booking BK-2026-11412.', actor: 'Arjun Mehta', timestamp: iso(-45 * 60 * 1000) },
      { id: 'e16', type: 'LAUNCHED', message: 'Auction launched with 3 invited vendors.', actor: 'Arjun Mehta', timestamp: iso(-15 * 60 * 1000) },
    ],
  },
  {
    id: 'AUC-SPOT-054',
    title: 'Spot | BK-2026-11501 | Chennai → Hyderabad',
    type: 'SPOT',
    status: 'UPCOMING',
    createdBy: 'Arjun Mehta',
    createdByRole: 'OPS',
    createdAt: iso(-90 * 60 * 1000),
    bookingId: 'BK-2026-11501',
    minBidDecrement: 150,
    extensionTriggerMinutes: 5,
    extensionDurationMinutes: 5,
    maxExtensions: 2,
    biddingWindowMinutes: 25,
    awardDeadline: iso(4 * 60 * 60 * 1000),
    invitedVendorIds: ['ven-1', 'ven-3'],
    lanes: [
      {
        id: 'lane-spot-3',
        lane: 'Chennai → Hyderabad',
        region: 'South India',
        vehicleType: '20 MT Open Body',
        capacityMt: 20,
        rateUnit: 'PER_TRIP',
        ceilingRate: 35500,
        estimatedTrips: 1,
        basePriceSource: 'MANUAL',
        allocationMode: 'SINGLE',
        allocation: { r1: 100, r2: 0, r3: 0 },
        eligibleVendorIds: ['ven-1', 'ven-3'],
        timerEndsAt: iso(25 * 60 * 1000),
        extensionCount: 0,
        bidCount: 0,
        ranking: [],
      },
    ],
    auditTrail: [
      { id: 'e17', type: 'CREATED', message: 'Spot auction draft created from booking BK-2026-11501.', actor: 'Arjun Mehta', timestamp: iso(-90 * 60 * 1000) },
    ],
  },
  {
    id: 'AUC-SPOT-055',
    title: 'Spot | BK-2026-11544 | Pune → Nagpur',
    type: 'SPOT',
    status: 'AWARDED',
    createdBy: 'Arjun Mehta',
    createdByRole: 'OPS',
    createdAt: iso(-4 * 60 * 60 * 1000),
    startAt: iso(-3 * 60 * 60 * 1000),
    completedAt: iso(-30 * 60 * 1000),
    bookingId: 'BK-2026-11544',
    minBidDecrement: 150,
    extensionTriggerMinutes: 5,
    extensionDurationMinutes: 5,
    maxExtensions: 2,
    biddingWindowMinutes: 30,
    awardDeadline: iso(-10 * 60 * 1000),
    invitedVendorIds: ['ven-2', 'ven-4'],
    lanes: [
      {
        id: 'lane-spot-4',
        lane: 'Pune → Nagpur',
        region: 'West India',
        vehicleType: '14 MT Closed Body',
        capacityMt: 14,
        rateUnit: 'PER_TRIP',
        ceilingRate: 26500,
        estimatedTrips: 1,
        basePriceSource: 'MANUAL',
        allocationMode: 'SINGLE',
        allocation: { r1: 100, r2: 0, r3: 0 },
        eligibleVendorIds: ['ven-2', 'ven-4'],
        timerEndsAt: iso(-40 * 60 * 1000),
        extensionCount: 1,
        bidCount: 5,
        ranking: [
          { rank: 1, vendorId: 'ven-2', vendorName: 'BlueAxle Freight', amount: 24800, timestamp: iso(-35 * 60 * 1000) },
          { rank: 2, vendorId: 'ven-4', vendorName: 'MetroFleet Movers', amount: 25050, timestamp: iso(-37 * 60 * 1000) },
        ],
      },
    ],
    auditTrail: [
      { id: 'e18', type: 'CREATED', message: 'Spot auction draft created from booking BK-2026-11544.', actor: 'Arjun Mehta', timestamp: iso(-4 * 60 * 60 * 1000) },
      { id: 'e19', type: 'LAUNCHED', message: 'Auction launched with 2 invited vendors.', actor: 'Arjun Mehta', timestamp: iso(-3 * 60 * 60 * 1000) },
      { id: 'e20', type: 'AWARDED', message: 'Auction awarded to the top bidder.', actor: 'System', timestamp: iso(-30 * 60 * 1000) },
    ],
  },
  {
    id: 'AUC-SPOT-056',
    title: 'Spot | BK-2026-11580 | Jaipur → Indore',
    type: 'SPOT',
    status: 'CANCELLED',
    createdBy: 'Arjun Mehta',
    createdByRole: 'OPS',
    createdAt: iso(-6 * 60 * 60 * 1000),
    bookingId: 'BK-2026-11580',
    minBidDecrement: 150,
    extensionTriggerMinutes: 5,
    extensionDurationMinutes: 5,
    maxExtensions: 2,
    biddingWindowMinutes: 20,
    awardDeadline: iso(-2 * 60 * 60 * 1000),
    invitedVendorIds: ['ven-1', 'ven-2', 'ven-3'],
    lanes: [
      {
        id: 'lane-spot-5',
        lane: 'Jaipur → Indore',
        region: 'North India',
        vehicleType: '20 MT Open Body',
        capacityMt: 20,
        rateUnit: 'PER_TRIP',
        ceilingRate: 30500,
        estimatedTrips: 1,
        basePriceSource: 'MANUAL',
        allocationMode: 'SINGLE',
        allocation: { r1: 100, r2: 0, r3: 0 },
        eligibleVendorIds: ['ven-1', 'ven-2', 'ven-3'],
        timerEndsAt: iso(-5 * 60 * 60 * 1000),
        extensionCount: 0,
        bidCount: 2,
        ranking: [
          { rank: 1, vendorId: 'ven-3', vendorName: 'RoadBridge Carriers', amount: 28900, timestamp: iso(-4 * 60 * 60 * 1000) },
        ],
      },
    ],
    auditTrail: [
      { id: 'e21', type: 'CREATED', message: 'Spot auction draft created from booking BK-2026-11580.', actor: 'Arjun Mehta', timestamp: iso(-6 * 60 * 60 * 1000) },
      { id: 'e22', type: 'CANCELLED', message: 'Auction cancelled due to a booking change.', actor: 'Arjun Mehta', timestamp: iso(-2 * 60 * 60 * 1000) },
    ],
  },
  {
    id: 'AUC-SPOT-057',
    title: 'Spot | BK-2026-11601 | Draft',
    type: 'SPOT',
    status: 'DRAFT',
    createdBy: 'Arjun Mehta',
    createdByRole: 'OPS',
    createdAt: iso(-8 * 60 * 60 * 1000),
    bookingId: 'BK-2026-11601',
    minBidDecrement: 150,
    extensionTriggerMinutes: 5,
    extensionDurationMinutes: 5,
    maxExtensions: 2,
    biddingWindowMinutes: 20,
    awardDeadline: iso(5 * 60 * 60 * 1000),
    invitedVendorIds: ['ven-1', 'ven-2'],
    lanes: [
      {
        id: 'lane-spot-6',
        lane: 'Surat → Mumbai',
        region: 'West India',
        vehicleType: '20 MT Open Body',
        capacityMt: 20,
        rateUnit: 'PER_TRIP',
        ceilingRate: 31500,
        estimatedTrips: 1,
        basePriceSource: 'MANUAL',
        allocationMode: 'SINGLE',
        allocation: { r1: 100, r2: 0, r3: 0 },
        eligibleVendorIds: ['ven-1', 'ven-2'],
        timerEndsAt: iso(20 * 60 * 1000),
        extensionCount: 0,
        bidCount: 0,
        ranking: [],
      },
    ],
    auditTrail: [{ id: 'e23', type: 'CREATED', message: 'Spot auction draft saved.', actor: 'Arjun Mehta', timestamp: iso(-8 * 60 * 60 * 1000) }],
  },
  {
    id: 'AUC-SPOT-058',
    title: 'Spot | BK-2026-11612 | No Bids',
    type: 'SPOT',
    status: 'NO_BIDS',
    createdBy: 'Arjun Mehta',
    createdByRole: 'OPS',
    createdAt: iso(-9 * 60 * 60 * 1000),
    startAt: iso(-8 * 60 * 60 * 1000),
    completedAt: iso(-7 * 60 * 60 * 1000),
    bookingId: 'BK-2026-11612',
    minBidDecrement: 150,
    extensionTriggerMinutes: 5,
    extensionDurationMinutes: 5,
    maxExtensions: 2,
    biddingWindowMinutes: 20,
    awardDeadline: iso(-6 * 60 * 60 * 1000),
    invitedVendorIds: ['ven-3', 'ven-4'],
    lanes: [
      {
        id: 'lane-spot-7',
        lane: 'Delhi → Jaipur',
        region: 'North India',
        vehicleType: '20 MT Open Body',
        capacityMt: 20,
        rateUnit: 'PER_TRIP',
        ceilingRate: 27500,
        estimatedTrips: 1,
        basePriceSource: 'MANUAL',
        allocationMode: 'SINGLE',
        allocation: { r1: 100, r2: 0, r3: 0 },
        eligibleVendorIds: ['ven-3', 'ven-4'],
        timerEndsAt: iso(-7 * 60 * 60 * 1000),
        extensionCount: 0,
        bidCount: 0,
        ranking: [],
      },
    ],
    auditTrail: [
      { id: 'e24', type: 'CREATED', message: 'Spot auction draft created.', actor: 'Arjun Mehta', timestamp: iso(-9 * 60 * 60 * 1000) },
      { id: 'e25', type: 'LAUNCHED', message: 'Auction launched.', actor: 'Arjun Mehta', timestamp: iso(-8 * 60 * 60 * 1000) },
      { id: 'e26', type: 'COMPLETED', message: 'Auction ended without any valid bids.', actor: 'System', timestamp: iso(-7 * 60 * 60 * 1000) },
    ],
  },
  {
    id: 'AUC-BULK-020',
    title: 'Bulk | East Zone Milk Run',
    type: 'BULK',
    status: 'LIVE',
    createdBy: 'Naina Kapoor',
    createdByRole: 'PROCUREMENT',
    createdAt: iso(-2 * 60 * 60 * 1000),
    startAt: iso(-25 * 60 * 1000),
    minBidDecrement: 200,
    extensionTriggerMinutes: 5,
    extensionDurationMinutes: 5,
    maxExtensions: 3,
    biddingWindowMinutes: 1440,
    awardDeadline: iso(3 * 60 * 60 * 1000),
    invitedVendorIds: ['ven-1', 'ven-2', 'ven-3'],
    lanes: [
      {
        id: 'lane-bulk-4',
        lane: 'Kolkata → Patna',
        region: 'East India',
        vehicleType: '20 MT Open Body',
        capacityMt: 20,
        rateUnit: 'PER_TRIP',
        ceilingRate: 7800,
        estimatedTrips: 260,
        basePriceSource: 'MANUAL',
        allocationMode: 'SPLIT',
        allocation: { r1: 50, r2: 30, r3: 20 },
        eligibleVendorIds: ['ven-1', 'ven-2', 'ven-3'],
        timerEndsAt: iso(35 * 60 * 1000),
        extensionCount: 0,
        bidCount: 7,
        ranking: [
          { rank: 1, vendorId: 'ven-1', vendorName: 'SwiftHaul Logistics', amount: 7200, timestamp: iso(-12 * 60 * 1000) },
          { rank: 2, vendorId: 'ven-2', vendorName: 'BlueAxle Freight', amount: 7350, timestamp: iso(-15 * 60 * 1000) },
        ],
      },
      {
        id: 'lane-bulk-5',
        lane: 'Patna → Ranchi',
        region: 'East India',
        vehicleType: '14 MT Open Body',
        capacityMt: 14,
        rateUnit: 'PER_KM',
        ceilingRate: 9200,
        estimatedTrips: 180,
        basePriceSource: 'MANUAL',
        allocationMode: 'SINGLE',
        allocation: { r1: 100, r2: 0, r3: 0 },
        eligibleVendorIds: ['ven-2', 'ven-3'],
        timerEndsAt: iso(35 * 60 * 1000),
        extensionCount: 0,
        bidCount: 3,
        ranking: [
          { rank: 1, vendorId: 'ven-3', vendorName: 'RoadBridge Carriers', amount: 8600, timestamp: iso(-14 * 60 * 1000) },
        ],
      },
    ],
    auditTrail: [
      { id: 'e23', type: 'CREATED', message: 'Bulk auction draft created for East Zone.', actor: 'Naina Kapoor', timestamp: iso(-2 * 60 * 60 * 1000) },
      { id: 'e24', type: 'LAUNCHED', message: 'Auction launched.', actor: 'Naina Kapoor', timestamp: iso(-25 * 60 * 1000) },
    ],
  },
  {
    id: 'AUC-BULK-021',
    title: 'Bulk | Central Corridor Milk Run',
    type: 'BULK',
    status: 'COMPLETED',
    createdBy: 'Naina Kapoor',
    createdByRole: 'PROCUREMENT',
    createdAt: iso(-6 * 24 * 60 * 60 * 1000),
    startAt: iso(-5 * 24 * 60 * 60 * 1000),
    completedAt: iso(-9 * 60 * 60 * 1000),
    contractStartDate: dateOnly(20 * 24 * 60 * 60 * 1000),
    contractEndDate: dateOnly(200 * 24 * 60 * 60 * 1000),
    minBidDecrement: 200,
    extensionTriggerMinutes: 5,
    extensionDurationMinutes: 5,
    maxExtensions: 3,
    biddingWindowMinutes: 1440,
    awardDeadline: iso(2 * 60 * 60 * 1000),
    invitedVendorIds: ['ven-1', 'ven-2', 'ven-4'],
    lanes: [
      {
        id: 'lane-bulk-6',
        lane: 'Delhi → Agra',
        region: 'North India',
        vehicleType: '14 MT Open Body',
        capacityMt: 14,
        rateUnit: 'PER_TRIP',
        ceilingRate: 6400,
        estimatedTrips: 190,
        basePriceSource: 'MANUAL',
        allocationMode: 'SPLIT',
        allocation: { r1: 70, r2: 20, r3: 10 },
        eligibleVendorIds: ['ven-1', 'ven-2', 'ven-4'],
        timerEndsAt: iso(-9 * 60 * 60 * 1000),
        extensionCount: 1,
        bidCount: 8,
        ranking: [
          { rank: 1, vendorId: 'ven-4', vendorName: 'MetroFleet Movers', amount: 6020, timestamp: iso(-10 * 60 * 60 * 1000) },
          { rank: 2, vendorId: 'ven-1', vendorName: 'SwiftHaul Logistics', amount: 6150, timestamp: iso(-11 * 60 * 60 * 1000) },
        ],
      },
      {
        id: 'lane-bulk-7',
        lane: 'Agra → Kanpur',
        region: 'North India',
        vehicleType: '14 MT Open Body',
        capacityMt: 14,
        rateUnit: 'PER_KM',
        ceilingRate: 7000,
        estimatedTrips: 150,
        basePriceSource: 'MANUAL',
        allocationMode: 'SINGLE',
        allocation: { r1: 100, r2: 0, r3: 0 },
        eligibleVendorIds: ['ven-2', 'ven-4'],
        timerEndsAt: iso(-9 * 60 * 60 * 1000),
        extensionCount: 0,
        bidCount: 4,
        ranking: [
          { rank: 1, vendorId: 'ven-2', vendorName: 'BlueAxle Freight', amount: 6550, timestamp: iso(-9.5 * 60 * 60 * 1000) },
        ],
      },
    ],
    auditTrail: [
      { id: 'e25', type: 'CREATED', message: 'Bulk auction draft created for Central Corridor.', actor: 'Naina Kapoor', timestamp: iso(-6 * 24 * 60 * 60 * 1000) },
      { id: 'e26', type: 'LAUNCHED', message: 'Auction launched.', actor: 'Naina Kapoor', timestamp: iso(-5 * 24 * 60 * 60 * 1000) },
      { id: 'e27', type: 'COMPLETED', message: 'Auction completed and pending award.', actor: 'System', timestamp: iso(-9 * 60 * 60 * 1000) },
    ],
  },
  {
    id: 'AUC-BULK-022',
    title: 'Bulk | South East Refill',
    type: 'BULK',
    status: 'CANCELLED',
    createdBy: 'Naina Kapoor',
    createdByRole: 'PROCUREMENT',
    createdAt: iso(-3 * 24 * 60 * 60 * 1000),
    startAt: iso(-2 * 24 * 60 * 60 * 1000),
    completedAt: iso(-30 * 60 * 1000),
    contractStartDate: dateOnly(40 * 24 * 60 * 60 * 1000),
    contractEndDate: dateOnly(220 * 24 * 60 * 60 * 1000),
    minBidDecrement: 200,
    extensionTriggerMinutes: 5,
    extensionDurationMinutes: 5,
    maxExtensions: 3,
    biddingWindowMinutes: 1440,
    awardDeadline: iso(1 * 60 * 60 * 1000),
    invitedVendorIds: ['ven-2', 'ven-3', 'ven-4'],
    lanes: [
      {
        id: 'lane-bulk-8',
        lane: 'Hyderabad → Vijayawada',
        region: 'South India',
        vehicleType: '20 MT Open Body',
        capacityMt: 20,
        rateUnit: 'PER_TRIP',
        ceilingRate: 8600,
        estimatedTrips: 210,
        basePriceSource: 'MANUAL',
        allocationMode: 'SINGLE',
        allocation: { r1: 100, r2: 0, r3: 0 },
        eligibleVendorIds: ['ven-2', 'ven-3', 'ven-4'],
        timerEndsAt: iso(-30 * 60 * 1000),
        extensionCount: 0,
        bidCount: 0,
        ranking: [],
      },
    ],
    auditTrail: [
      { id: 'e28', type: 'CREATED', message: 'Bulk auction draft created.', actor: 'Naina Kapoor', timestamp: iso(-3 * 24 * 60 * 60 * 1000) },
      { id: 'e29', type: 'CANCELLED', message: 'Auction cancelled before final evaluation.', actor: 'Naina Kapoor', timestamp: iso(-30 * 60 * 1000) },
    ],
  },
  {
    id: 'AUC-BULK-023',
    title: 'Bulk | Draft Lane Mix',
    type: 'BULK',
    status: 'DRAFT',
    createdBy: 'Naina Kapoor',
    createdByRole: 'PROCUREMENT',
    createdAt: iso(-6 * 60 * 60 * 1000),
    bookingId: 'BK-2026-11650',
    minBidDecrement: 200,
    extensionTriggerMinutes: 5,
    extensionDurationMinutes: 5,
    maxExtensions: 3,
    biddingWindowMinutes: 1440,
    awardDeadline: iso(4 * 60 * 60 * 1000),
    invitedVendorIds: ['ven-1', 'ven-2', 'ven-3'],
    lanes: [
      {
        id: 'lane-bulk-9',
        lane: 'Pune → Goa',
        region: 'West India',
        vehicleType: '20 MT Open Body',
        capacityMt: 20,
        rateUnit: 'PER_TRIP',
        ceilingRate: 8400,
        estimatedTrips: 210,
        basePriceSource: 'MANUAL',
        allocationMode: 'SPLIT',
        allocation: { r1: 60, r2: 30, r3: 10 },
        eligibleVendorIds: ['ven-1', 'ven-2', 'ven-3'],
        timerEndsAt: iso(2 * 60 * 60 * 1000),
        extensionCount: 0,
        bidCount: 0,
        ranking: [],
      },
    ],
    auditTrail: [{ id: 'e30', type: 'CREATED', message: 'Bulk auction draft saved.', actor: 'Naina Kapoor', timestamp: iso(-6 * 60 * 60 * 1000) }],
  },
  {
    id: 'AUC-BULK-024',
    title: 'Bulk | No Bids Route',
    type: 'BULK',
    status: 'NO_BIDS',
    createdBy: 'Naina Kapoor',
    createdByRole: 'PROCUREMENT',
    createdAt: iso(-8 * 24 * 60 * 60 * 1000),
    startAt: iso(-7 * 24 * 60 * 60 * 1000),
    completedAt: iso(-7 * 24 * 60 * 60 * 1000),
    minBidDecrement: 200,
    extensionTriggerMinutes: 5,
    extensionDurationMinutes: 5,
    maxExtensions: 3,
    biddingWindowMinutes: 1440,
    awardDeadline: iso(-6 * 24 * 60 * 60 * 1000),
    invitedVendorIds: ['ven-2', 'ven-4'],
    lanes: [
      {
        id: 'lane-bulk-10',
        lane: 'Chennai → Coimbatore',
        region: 'South India',
        vehicleType: '14 MT Open Body',
        capacityMt: 14,
        rateUnit: 'PER_TRIP',
        ceilingRate: 7100,
        estimatedTrips: 130,
        basePriceSource: 'MANUAL',
        allocationMode: 'SINGLE',
        allocation: { r1: 100, r2: 0, r3: 0 },
        eligibleVendorIds: ['ven-2', 'ven-4'],
        timerEndsAt: iso(-7 * 24 * 60 * 60 * 1000),
        extensionCount: 0,
        bidCount: 0,
        ranking: [],
      },
    ],
    auditTrail: [
      { id: 'e31', type: 'CREATED', message: 'Bulk auction draft created.', actor: 'Naina Kapoor', timestamp: iso(-8 * 24 * 60 * 60 * 1000) },
      { id: 'e32', type: 'LAUNCHED', message: 'Auction launched.', actor: 'Naina Kapoor', timestamp: iso(-7 * 24 * 60 * 60 * 1000) },
      { id: 'e33', type: 'COMPLETED', message: 'Auction ended without any valid bids.', actor: 'System', timestamp: iso(-7 * 24 * 60 * 60 * 1000) },
    ],
  },
  {
    id: 'AUC-LOT-012',
    title: 'Lot | West Hub Consolidation',
    type: 'LOT',
    status: 'UPCOMING',
    createdBy: 'Naina Kapoor',
    createdByRole: 'PROCUREMENT',
    createdAt: iso(-12 * 60 * 60 * 1000),
    region: 'West India',
    minBidDecrement: 250,
    extensionTriggerMinutes: 5,
    extensionDurationMinutes: 5,
    maxExtensions: 3,
    biddingWindowMinutes: 2880,
    awardDeadline: iso(6 * 60 * 60 * 1000),
    invitedVendorIds: ['ven-1', 'ven-2', 'ven-4'],
    lanes: [
      {
        id: 'lane-lot-2',
        lane: 'Mumbai → Surat',
        region: 'West India',
        vehicleType: '32 FT Closed Body',
        capacityMt: 32,
        rateUnit: 'PER_MT',
        ceilingRate: 13600,
        estimatedTrips: 160,
        basePriceSource: 'MANUAL',
        allocationMode: 'SPLIT',
        allocation: { r1: 70, r2: 20, r3: 10 },
        eligibleVendorIds: ['ven-1', 'ven-2', 'ven-4'],
        timerEndsAt: iso(8 * 60 * 60 * 1000),
        extensionCount: 0,
        bidCount: 0,
        ranking: [],
      },
      {
        id: 'lane-lot-3',
        lane: 'Surat → Ahmedabad',
        region: 'West India',
        vehicleType: '32 FT Closed Body',
        capacityMt: 32,
        rateUnit: 'PER_MT',
        ceilingRate: 13200,
        estimatedTrips: 140,
        basePriceSource: 'MANUAL',
        allocationMode: 'SINGLE',
        allocation: { r1: 100, r2: 0, r3: 0 },
        eligibleVendorIds: ['ven-1', 'ven-2'],
        timerEndsAt: iso(8 * 60 * 60 * 1000),
        extensionCount: 0,
        bidCount: 0,
        ranking: [],
      },
    ],
    auditTrail: [
      { id: 'e30', type: 'CREATED', message: 'Lot auction draft created for West Hub Consolidation.', actor: 'Naina Kapoor', timestamp: iso(-12 * 60 * 60 * 1000) },
    ],
  },
  {
    id: 'AUC-LOT-013',
    title: 'Lot | East Corridor Distribution',
    type: 'LOT',
    status: 'LIVE',
    createdBy: 'Naina Kapoor',
    createdByRole: 'PROCUREMENT',
    createdAt: iso(-10 * 60 * 60 * 1000),
    startAt: iso(-2 * 60 * 60 * 1000),
    minBidDecrement: 250,
    extensionTriggerMinutes: 5,
    extensionDurationMinutes: 5,
    maxExtensions: 3,
    biddingWindowMinutes: 2880,
    region: 'East India',
    awardDeadline: iso(90 * 60 * 1000),
    invitedVendorIds: ['ven-1', 'ven-2', 'ven-3', 'ven-4'],
    lanes: [
      {
        id: 'lane-lot-4',
        lane: 'Kolkata → Guwahati',
        region: 'East India',
        vehicleType: '32 FT Closed Body',
        capacityMt: 32,
        rateUnit: 'PER_TRIP',
        ceilingRate: 15100,
        estimatedTrips: 200,
        basePriceSource: 'MANUAL',
        allocationMode: 'SPLIT',
        allocation: { r1: 60, r2: 30, r3: 10 },
        eligibleVendorIds: ['ven-1', 'ven-2', 'ven-3', 'ven-4'],
        timerEndsAt: iso(45 * 60 * 1000),
        extensionCount: 0,
        bidCount: 5,
        ranking: [
          { rank: 1, vendorId: 'ven-3', vendorName: 'RoadBridge Carriers', amount: 14200, timestamp: iso(-20 * 60 * 1000) },
        ],
      },
    ],
    auditTrail: [
      { id: 'e31', type: 'CREATED', message: 'Lot auction draft created for East Corridor.', actor: 'Naina Kapoor', timestamp: iso(-10 * 60 * 60 * 1000) },
      { id: 'e32', type: 'LAUNCHED', message: 'Auction launched.', actor: 'Naina Kapoor', timestamp: iso(-2 * 60 * 60 * 1000) },
    ],
  },
  {
    id: 'AUC-LOT-014',
    title: 'Lot | North Express Allocation',
    type: 'LOT',
    status: 'AWARDED',
    createdBy: 'Naina Kapoor',
    createdByRole: 'PROCUREMENT',
    createdAt: iso(-18 * 24 * 60 * 60 * 1000),
    startAt: iso(-17 * 24 * 60 * 60 * 1000),
    completedAt: iso(-16 * 24 * 60 * 60 * 1000),
    contractStartDate: dateOnly(-1 * 24 * 60 * 60 * 1000),
    contractEndDate: dateOnly(180 * 24 * 60 * 60 * 1000),
    minBidDecrement: 250,
    extensionTriggerMinutes: 5,
    extensionDurationMinutes: 5,
    maxExtensions: 3,
    biddingWindowMinutes: 2880,
    region: 'North India',
    awardDeadline: iso(-15 * 24 * 60 * 60 * 1000),
    invitedVendorIds: ['ven-1', 'ven-2', 'ven-3', 'ven-4'],
    lanes: [
      {
        id: 'lane-lot-5',
        lane: 'Delhi → Kanpur',
        region: 'North India',
        vehicleType: '32 FT Closed Body',
        capacityMt: 32,
        rateUnit: 'PER_MT',
        ceilingRate: 14900,
        estimatedTrips: 210,
        basePriceSource: 'MANUAL',
        allocationMode: 'SPLIT',
        allocation: { r1: 70, r2: 20, r3: 10 },
        eligibleVendorIds: ['ven-1', 'ven-2', 'ven-3', 'ven-4'],
        timerEndsAt: iso(-16 * 24 * 60 * 60 * 1000),
        extensionCount: 2,
        bidCount: 10,
        ranking: [
          { rank: 1, vendorId: 'ven-2', vendorName: 'BlueAxle Freight', amount: 13850, timestamp: iso(-17 * 24 * 60 * 60 * 1000) },
          { rank: 2, vendorId: 'ven-4', vendorName: 'MetroFleet Movers', amount: 13990, timestamp: iso(-17.1 * 24 * 60 * 60 * 1000) },
        ],
      },
      {
        id: 'lane-lot-6',
        lane: 'Kanpur → Lucknow',
        region: 'North India',
        vehicleType: '32 FT Closed Body',
        capacityMt: 32,
        rateUnit: 'PER_MT',
        ceilingRate: 14600,
        estimatedTrips: 190,
        basePriceSource: 'MANUAL',
        allocationMode: 'SINGLE',
        allocation: { r1: 100, r2: 0, r3: 0 },
        eligibleVendorIds: ['ven-1', 'ven-2'],
        timerEndsAt: iso(-16 * 24 * 60 * 60 * 1000),
        extensionCount: 1,
        bidCount: 6,
        ranking: [
          { rank: 1, vendorId: 'ven-1', vendorName: 'SwiftHaul Logistics', amount: 13400, timestamp: iso(-17 * 24 * 60 * 60 * 1000) },
        ],
      },
    ],
    auditTrail: [
      { id: 'e33', type: 'CREATED', message: 'Lot auction draft created for North Express Allocation.', actor: 'Naina Kapoor', timestamp: iso(-18 * 24 * 60 * 60 * 1000) },
      { id: 'e34', type: 'LAUNCHED', message: 'Auction launched.', actor: 'Naina Kapoor', timestamp: iso(-17 * 24 * 60 * 60 * 1000) },
      { id: 'e35', type: 'AWARDED', message: 'Award completed for all lanes.', actor: 'System', timestamp: iso(-16 * 24 * 60 * 60 * 1000) },
    ],
  },
  {
    id: 'AUC-LOT-015',
    title: 'Lot | South Distribution Rebid',
    type: 'LOT',
    status: 'NO_BIDS',
    createdBy: 'Naina Kapoor',
    createdByRole: 'PROCUREMENT',
    createdAt: iso(-7 * 24 * 60 * 60 * 1000),
    startAt: iso(-6 * 24 * 60 * 60 * 1000),
    completedAt: iso(-5 * 24 * 60 * 60 * 1000),
    minBidDecrement: 250,
    extensionTriggerMinutes: 5,
    extensionDurationMinutes: 5,
    maxExtensions: 3,
    biddingWindowMinutes: 2880,
    region: 'South India',
    awardDeadline: iso(-4 * 24 * 60 * 60 * 1000),
    invitedVendorIds: ['ven-2', 'ven-3'],
    lanes: [
      {
        id: 'lane-lot-7',
        lane: 'Bangalore → Mysore',
        region: 'South India',
        vehicleType: '20 MT Open Body',
        capacityMt: 20,
        rateUnit: 'PER_TRIP',
        ceilingRate: 9200,
        estimatedTrips: 120,
        basePriceSource: 'MANUAL',
        allocationMode: 'SINGLE',
        allocation: { r1: 100, r2: 0, r3: 0 },
        eligibleVendorIds: ['ven-2', 'ven-3'],
        timerEndsAt: iso(-5 * 24 * 60 * 60 * 1000),
        extensionCount: 0,
        bidCount: 0,
        ranking: [],
      },
    ],
    auditTrail: [
      { id: 'e36', type: 'CREATED', message: 'Lot auction draft created for South Distribution Rebid.', actor: 'Naina Kapoor', timestamp: iso(-7 * 24 * 60 * 60 * 1000) },
      { id: 'e37', type: 'LAUNCHED', message: 'Auction launched.', actor: 'Naina Kapoor', timestamp: iso(-6 * 24 * 60 * 60 * 1000) },
      { id: 'e38', type: 'COMPLETED', message: 'Auction ended with zero valid bids.', actor: 'System', timestamp: iso(-5 * 24 * 60 * 60 * 1000) },
    ],
  },
  {
    id: 'AUC-LOT-016',
    title: 'Lot | Draft West Cluster',
    type: 'LOT',
    status: 'DRAFT',
    createdBy: 'Naina Kapoor',
    createdByRole: 'PROCUREMENT',
    createdAt: iso(-7 * 60 * 60 * 1000),
    region: 'West India',
    minBidDecrement: 250,
    extensionTriggerMinutes: 5,
    extensionDurationMinutes: 5,
    maxExtensions: 3,
    biddingWindowMinutes: 2880,
    awardDeadline: iso(7 * 60 * 60 * 1000),
    invitedVendorIds: ['ven-1', 'ven-2', 'ven-3'],
    lanes: [
      {
        id: 'lane-lot-8',
        lane: 'Pune → Nashik',
        region: 'West India',
        vehicleType: '32 FT Closed Body',
        capacityMt: 32,
        rateUnit: 'PER_MT',
        ceilingRate: 12800,
        estimatedTrips: 145,
        basePriceSource: 'MANUAL',
        allocationMode: 'SPLIT',
        allocation: { r1: 70, r2: 20, r3: 10 },
        eligibleVendorIds: ['ven-1', 'ven-2', 'ven-3'],
        timerEndsAt: iso(7 * 60 * 60 * 1000),
        extensionCount: 0,
        bidCount: 0,
        ranking: [],
      },
    ],
    auditTrail: [{ id: 'e39', type: 'CREATED', message: 'Lot auction draft saved.', actor: 'Naina Kapoor', timestamp: iso(-7 * 60 * 60 * 1000) }],
  },
  {
    id: 'AUC-LOT-017',
    title: 'Lot | No Bids North Link',
    type: 'LOT',
    status: 'NO_BIDS',
    createdBy: 'Naina Kapoor',
    createdByRole: 'PROCUREMENT',
    createdAt: iso(-9 * 24 * 60 * 60 * 1000),
    startAt: iso(-8 * 24 * 60 * 60 * 1000),
    completedAt: iso(-8 * 24 * 60 * 60 * 1000),
    minBidDecrement: 250,
    extensionTriggerMinutes: 5,
    extensionDurationMinutes: 5,
    maxExtensions: 3,
    biddingWindowMinutes: 2880,
    region: 'North India',
    awardDeadline: iso(-7 * 24 * 60 * 60 * 1000),
    invitedVendorIds: ['ven-2', 'ven-4'],
    lanes: [
      {
        id: 'lane-lot-9',
        lane: 'Lucknow → Kanpur',
        region: 'North India',
        vehicleType: '32 FT Closed Body',
        capacityMt: 32,
        rateUnit: 'PER_MT',
        ceilingRate: 9400,
        estimatedTrips: 110,
        basePriceSource: 'MANUAL',
        allocationMode: 'SINGLE',
        allocation: { r1: 100, r2: 0, r3: 0 },
        eligibleVendorIds: ['ven-2', 'ven-4'],
        timerEndsAt: iso(-8 * 24 * 60 * 60 * 1000),
        extensionCount: 0,
        bidCount: 0,
        ranking: [],
      },
    ],
    auditTrail: [
      { id: 'e40', type: 'CREATED', message: 'Lot auction draft created.', actor: 'Naina Kapoor', timestamp: iso(-9 * 24 * 60 * 60 * 1000) },
      { id: 'e41', type: 'LAUNCHED', message: 'Auction launched.', actor: 'Naina Kapoor', timestamp: iso(-8 * 24 * 60 * 60 * 1000) },
      { id: 'e42', type: 'COMPLETED', message: 'Auction ended without any valid bids.', actor: 'System', timestamp: iso(-8 * 24 * 60 * 60 * 1000) },
    ],
  },
]

export const MOCK_CONTRACTS: Contract[] = [
  {
    id: 'CNT-2026-0101',
    sourceAuctionId: 'AUC-LEGACY-LOT-001',
    contractType: 'LOT',
    vendorId: 'ven-2',
    vendorName: 'BlueAxle Freight',
    lane: 'Delhi → Lucknow',
    region: 'North India',
    vehicleType: '32 FT Closed Body',
    contractedRate: 13100,
    rateUnit: 'PER_MT',
    volumeAllocationPercent: 70,
    allocationRank: 'R1',
    startDate: dateOnly(-4 * 24 * 60 * 60 * 1000),
    endDate: dateOnly(175 * 24 * 60 * 60 * 1000),
    estimatedTrips: 220,
    status: 'ACTIVE',
    r1OverrideReason: 'R1 assigned to the R2 bidder due to recent placement failure scorecard for MetroFleet Movers.',
    rateSyncedToTms: true,
    placementFailures: [],
    rateDeviationOpen: false,
  },
  {
    id: 'CNT-2026-0102',
    sourceAuctionId: 'AUC-LEGACY-LOT-001',
    contractType: 'LOT',
    vendorId: 'ven-4',
    vendorName: 'MetroFleet Movers',
    lane: 'Delhi → Lucknow',
    region: 'North India',
    vehicleType: '32 FT Closed Body',
    contractedRate: 12900,
    rateUnit: 'PER_MT',
    volumeAllocationPercent: 20,
    allocationRank: 'R2',
    startDate: dateOnly(-4 * 24 * 60 * 60 * 1000),
    endDate: dateOnly(175 * 24 * 60 * 60 * 1000),
    estimatedTrips: 220,
    status: 'ACTIVE',
    rateSyncedToTms: true,
    placementFailures: [],
    rateDeviationOpen: false,
  },
  {
    id: 'CNT-2026-0103',
    sourceAuctionId: 'AUC-LEGACY-LOT-001',
    contractType: 'LOT',
    vendorId: 'ven-1',
    vendorName: 'SwiftHaul Logistics',
    lane: 'Delhi → Lucknow',
    region: 'North India',
    vehicleType: '32 FT Closed Body',
    contractedRate: 13250,
    rateUnit: 'PER_MT',
    volumeAllocationPercent: 10,
    allocationRank: 'R3',
    startDate: dateOnly(-4 * 24 * 60 * 60 * 1000),
    endDate: dateOnly(175 * 24 * 60 * 60 * 1000),
    estimatedTrips: 220,
    status: 'ACTIVE',
    rateSyncedToTms: true,
    placementFailures: [],
    rateDeviationOpen: false,
  },
  {
    id: 'CNT-2026-0117',
    sourceAuctionId: 'AUC-LEGACY-BULK-001',
    contractType: 'BULK',
    vendorId: 'ven-3',
    vendorName: 'RoadBridge Carriers',
    lane: 'Pune → Jaipur',
    region: 'West India',
    vehicleType: '32 FT Closed Body',
    contractedRate: 48800,
    rateUnit: 'PER_TRIP',
    volumeAllocationPercent: 100,
    allocationRank: 'R1',
    startDate: dateOnly(-40 * 24 * 60 * 60 * 1000),
    endDate: dateOnly(10 * 24 * 60 * 60 * 1000),
    estimatedTrips: 75,
    status: 'EXPIRING_SOON',
    rateSyncedToTms: true,
    placementFailures: [
      {
        failedVendor: 'RoadBridge Carriers',
        replacementVendor: 'BlueAxle Freight',
        originalRate: 48800,
        replacementRate: 51200,
        differential: 2400,
        debitNoteTriggered: true,
      },
    ],
    rateDeviationOpen: true,
  },
]
